### ISSUE TITLE
Old Documentation?

### ISSUE THREAD

**Issue by Ductayp** [Sleitnick/Knit#170]
I am using Knit for quite a while now, and the new version is vastly different, especially in the Utilities, to where I cant fathom updating. Some of the utilities I use are changed, such as RemoteSignal is now somehow dependant on somethign called midlleware which seems unecesarily complex.

I dont have wally, and just installing a few packages into my roblox game takes a tiny amount of time, not sure why I would need it.

I need access to the old documentation, since thats the version of Knit i am using and will probably always use. Thanks!

**Comment by jwisham** [comment]
This works, but really should be documented somewhere.

**Comment by Sleitnick** [comment]
Old documentation can be found here: https://github.com/Sleitnick/Knit/tree/v0.0.22-alpha/docs

New documentation will be pulled in with the linked PR.
