### ISSUE TITLE
On the client, invoke a server function returns a promise

### ISSUE THREAD

**Issue by CaptinLetus** [Sleitnick/Knit#171]
It seems that when you do `service:Function()`, it always returns a promise

In the old Knit, you would need to do `service:FunctionPromise()`

I'm not sure if this is the intended behaviour.  If it is, the documentation should be updated

**Comment by Sleitnick** [comment]
Linked PR will make this change. e.g.:

```lua
-- Client / LocalScript
Knit.Start({
	ServicePromises = false; -- Defaults to `true`
})
```
