### ISSUE TITLE
Create Memoization Util

### ISSUE THREAD

**Issue by LuaBrowser** [Sleitnick/Knit#174]
Having a util to Memoize functions would promote the practice of optimizing your functions; and further increase the performance of the Knit Framework as it'd be returning already cached ``self`` or ``local`` variables, that is if the variable isn't in an ignore list.

**Comment by Sleitnick** [comment]
Hi! Unfortunately, such a function is out of scope for Knit's purpose. I do agree that memoizing is nice.
