### ISSUE TITLE
Knit.GetController within a Controller - Promise.Error

### ISSUE THREAD

**Issue by AvailableJosh** [Sleitnick/Knit#175]
Hello,

I have made multiple controllers, and I have required them all within my ClientRuntime.client.lua script, but I seem to have some problems with this.

I have one module called MenuController.lua, and another called CameraController.lua, and within my MenuController, I am showing the MainMenu GUI, and within the CameraController, I have a CameraController:Move() function that moves the camera to a position inputted as an argument within the function.

I have used Knit.GetController("CameraController") within my MenuController.lua script, and I am calling the CameraController:Move() function to move the camera to a different position, but sometimes when loading the game, I get a Promise error, and sometimes I don't get a Promise error. The error says that I "attempted to index nil with 'CameraController:Move()'.

**MenuController.lua**
```lua
local knit = require(game:GetService("ReplicatedStorage"):WaitForChild("Knit"))

local MenuController = knit.CreateController {
    Name = "MenuController"
}

local roact = require(game:GetService("ReplicatedStorage"):WaitForChild("Roact"))

local replicatedStorage = game:GetService("ReplicatedStorage")
local players = game:GetService("Players")

local player = players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")
local cameraPoints = workspace:WaitForChild("CameraPoints")
local menuCameraPoint = cameraPoints.MenuCameraPoint

local cameraController = knit.GetController("CameraController")

function MenuController:Create()
    local menu = roact.createElement("ScreenGui", {
        Name = "Menu",
        IgnoreGuiInset = true,
        ResetOnSpawn = false
    }, {
        Label = roact.createElement("TextLabel", {
            Name = "Label",
            Text = "Label"
        })
    })

    roact.mount(menu, playerGui, "MainMenu")
end

function MenuController:KnitStart()
    cameraController:Move(menuCameraPoint.CFrame)
    self:Create()
end

return MenuController
```

**CameraController.lua**
```lua
local knit = require(game:GetService("ReplicatedStorage"):WaitForChild("Knit"))

local CameraController = knit.CreateController {
    Name = "CameraController"
}

local camera = workspace.CurrentCamera

function CameraController:Move(position : CFrame)
    if position then
        repeat
            camera.CameraType = Enum.CameraType.Scriptable
        until camera.CameraType == Enum.CameraType.Scriptable

        camera.CFrame = position
    end
end

return CameraController
```

Does anyone have any idea why this may be happening, or if I am actually able to call Knit.GetController() within another controller?

**Comment by howmanysmall** [comment]
This is definitely on you. You're calling it before it exists.

**Comment by AvailableJosh** [comment]
> This is definitely on you. You're calling it before it exists. The only safe place to call it is in functions and KnitStart (not KnitInit).

This worked, thank you so much for your response and your help! :)
