### ISSUE TITLE
Race condition: client tries to access a service that has not been initialized yet

### ISSUE THREAD

**Issue by finobinos** [Sleitnick/Knit#180]
There is a race condition within Knit, where a client attempts to access a client-exposed service which has not been initialized in time. This isn't often, but can happen in large-scale games where important services which serve the backbone of a game, for e.g a data service which possibly can take longer to initialize for many reasons and I fear this race condition because I'm working on a large-scale project and services in my project will take some time to initialize and I'm already seeing race condition issues with this problem.

**Proposal**

`Knit.Start` (client) should expose another parameter, something like `WaitForServerToStart`. If `true`, it will first wait for Knit to start on the server before actually starting on the client. That way, I also get the freedom to freely access services via controllers without having to define them in the `KnitInit` stage and start using them in `KnitStart`.

```lua
-- Client
Knit.Start({WaitForServerToStart = true})
```

```lua
-- Example controller

-- Freely access services here (guaranteed to be initialized and ready to be used)
local SomeService = Knit.GetService("Service")

function controller:KnitInit()
      -- define controllers here, but dont yet use them
end

function controller:KnitStart()
      -- start using other controllers
end
```

**Comment by Sleitnick** [comment]
Thanks for the call-out!

I'm going to flip the flag around, and say that the _default_ should be to wait for the server to start unless flagged. E.g. maybe there's a `ClientOnly` option and that will skip the wait.

This should be fairly easy to implement.

**Comment by Sleitnick** [comment]
After review, the Services folder is only parented once all services have been started. And the client waits for that folder to exist. So the client can't utilize server-side services until they are ready. The client can run controllers and other things, but it will block when calling `GetService` until the server is ready. I think this is fine and expected behavior overall, and will prevent the race condition as far as I can see
