### ISSUE TITLE
Rephrasing concerning Studio workflow

### ISSUE THREAD

**Issue by Frqstbite** [Sleitnick/Knit#181]
Part of the documentation for Knit comes off as demeaning for Roblox Studio users.
The only instance of this I've found is [here](https://sleitnick.github.io/Knit/docs/intro#for-everyone), (where it implies Studio is for new users,) but there may be more.

I suggest referring to the users who prefer Rojo simply as "users who prefer professional-grade software."

**Comment by Sleitnick** [comment]
I agree that the language should change. It certainly seems to imply that people using the Studio workflow are less professional, which is not great. Thanks for the input! I will close this once the change is made.
