### ISSUE TITLE
Please update dependencies to the latest version.

### ISSUE THREAD

**Issue by Sparkypen7** [Sleitnick/Knit#191]
This is causing conflicts in other's project files.

Knit should pull promise to the latest `major` tag in SemVer pulled from Wally. 

To possibly avoid this issue, perhaps change `Promise = "evaera/promise@3.1"` to `Promise = "evaera/promise@^3"` instead.

Unfortunately, wally does not allow me to use evaera's latest version of promise as a dependent in my project, as long as I keep Knit as a dependent on my project.

This suggestion goes in hand with [this pull request](https://github.com/Sleitnick/Knit/pull/190).

**Comment by Sleitnick** [comment]
Should be fixed in https://github.com/Sleitnick/Knit/releases/tag/v1.4.2
