### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by CertifiedRice** [Sleitnick/Knit#204]
I there a way to use Knit with [roblox-ts](https://[roblox-ts](https://roblox-ts.com/).com/)?

**Comment by howmanysmall** [comment]
Yes. There's a package already.

**Comment by Ukendio** [comment]
> Yes. There's a package already. @osyrisrblx made it.

For the record, roblox-ts support has dropped for Knit completely from osyris. Not sure if anyone decided to take over, but basically anyone that is looking for a similar framework are directed to use Flamework by @fireboltofdeath
