### ISSUE TITLE
New methods for easier remoteSignal connections

### ISSUE THREAD

**Issue by CaptinLetus** [Sleitnick/Knit#208]
Currently, if a service has a lot of RemtoteSignals, it can make our KnitInit function very long with a bunch of connections.

Here is the current way of doing things:

```lua
local SomeService = Knit.CreateService {
	Name = "SomeService";
	Client = {
		SomeEvent = Knit.CreateSignal()
	};
}

function SomeService:KnitInit()
	self.Client.SomeEvent:Connect(function(...)
		self:EventConnection(...)
	end)
end

function SomeService:EventConnection(player, ...)
	print("player sent", ...)
end
```

It would be nice to have a built-in feature to Knit that would allow us to connect to events like so:

```lua
local SomeService = Knit.CreateService {
	Name = "SomeService";
	Client = {
		SomeEvent = Knit.CreateSignal()
	};
}

function SomeService.Client.SomeEvent:Connect(player, ...)
	print("player sent", ...)
end
```

Similar functions could be made for remote properties as well

**Comment by eAi** [comment]
I don’t think your syntax would quite work - but I think it’d be theoretically possible to make it so you could connect to signals outside KnitInit. I believe that signals aren’t actually created when you call CreateSignal - a placeholder is. This would prevent you connecting to it outside KnitInit - but that could be changed to allow functions to be registered and to copy over the connections when the signal is actually created.

This is something that’s frustrated me too so it would be nice to improve it!

**Comment by CaptinLetus** [comment]
Why dont you think the syntax would work?

**Comment by Sleitnick** [comment]
#248
