### ISSUE TITLE
Allow us to get access to uninitialized services / controllers

### ISSUE THREAD

**Issue by Weldify** [Sleitnick/Knit#210]
Currently, to get access to a service/controller, you have to use `.GetService()` and `.GetController()` respectively in the `:Start()` method of another controller. It looks something like this:
```lua
local MyController = Knit.CreateController {
	Name = "MyController",
}

local OtherController

function MyController:KnitStart()
	OtherController = Knit.GetController("OtherController")
end
```

While this is fine, I don't personally like spending 2 lines to get access to each controller and I feel like there could be a better way. It could go something like this:
```lua
local MyController = Knit.CreateController {
	Name = "MyController",
}

local OtherController = Knit.GetController("OtherController", true)

function MyController:KnitStart()
	-- no need for anything in here
end
```

I suggest adding an optional argument to `.GetService()` and `.GetController()` that allows you to access a service/controller before it gets initialized. 

Let me know what you think. I'd be happy to implement this and do a PR.

**Comment by kyojindev** [comment]
This is not possible because controllers and services are only added to Knit when required, meaning that Knit has no knowledge of the controller or service existing beforehand.

**Comment by Weldify** [comment]
This is possible. And I, in fact, know how to implement it as well. The concept goes as such:
When you use `.GetService()` with the optional argument, instead of erroring if the service isnt there, it will create a barebones dummy table including it's name and other required (although empty) fields like `.Client` for services. Then, when the service is actually created, all of the values from the service definition get copied into the existing table.

**Comment by bubshayz** [comment]
`.GetService()` with a boolean argument just to let the method return you the initialized service is **bad** practice, learn more about boolean parameters [here](https://medium.com/@amlcurran/clean-code-the-curse-of-a-boolean-parameter-c237a830b7a3). 

I'm not going to talk much about the concept but rather the fact that an additional method `GetUninitializedService` (or something similar to that) should rather be implemented, there should be **clear** distinction between `GetService` and the new method. Additionally, `GetService("service", true)` would immediately imply to the reader that the `true` argument is completely redundant here!

**Comment by EncodedVenom** [comment]
One potential solution to this is to have `.GetService()` calls before `Knit.Start()` return an empty table with metamethods that directly set the table after the start process is completed. That way, no unnecessary arguments or additional methods need to be used.

Issues such as non-existent services/controllers, indexing them before they are ready, etc, can be enforced using metamethods.

**Comment by EncodedVenom** [comment]
Out of curiosity, would incorporating this function that I just wrote up into `Knit.GetService` work?
```lua
local function getKnitService(service: string)
    return setmetatable({}, {
        __index = function(dummyTable)
            local success = Knit.OnStart():timeout(1/60):await() -- Hacky, but this is out of Knit's scope.
            if not success then
                error("Knit has not been initialized yet!")
            end
            local exists, serviceObjectOrWarning = pcall(function()
                return Knit.GetService(service)
            end)
            if not exists then
                setmetatable(dummyTable, {}) -- Don't create repetitive errors.
                error(serviceObjectOrWarning)
            end
            for k, v in pairs(serviceObjectOrWarning) do
                rawset(dummyTable, k, v)
            end
            setmetatable(dummyTable, {})
        end
    })
end
```

**Comment by Weldify** [comment]
Made a PR. 
https://github.com/Sleitnick/Knit/pull/211

**Comment by Sleitnick** [comment]
I think I'm a little uneasy with services existing in an unpopulated state. In other words, the returned service is not actually the service yet at all. The table ref returned is expected to be mutated (in an ideal world, services should have no mutations IMO, but Knit v2 will address that)

**Comment by 4x8Matrix** [comment]
@Sleitnick as mentioned, your uneasy with the idea of unpopulated services ~ instead could we introduce a method to get premature services? (This would keep services - as services, but premature services as a way to define a reference to an not-yet-set service; Which would also avoid tampering with Knit services as a whole. )

I primarily want this change to help make the codebase cleaner with the definitions of services and controllers references completed at the top

```lua
local Knit = require(path.to.Knit)

local SessionService = Knit.GetPrematureService("SessionService")
```
