### ISSUE TITLE
Something's wrong with Knit.AddServices()

### ISSUE THREAD

**Issue by FSXplay** [Sleitnick/Knit#212]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/95726321/177190658-e848d73f-5730-4aa9-8187-2f1420b43f10.png">

**Comment by howmanysmall** [comment]
You forgot to do a return. This is on you.

![image](https://user-images.githubusercontent.com/26746527/177191796-4029c049-83de-4aab-8bd0-401dccd28bf3.png)

**Comment by Sleitnick** [comment]
Hello! Please make sure that your service modules are returning the service. If a ModuleScript doesn't return anything, Roblox will throw this error. This is a Roblox-related error & not something that Knit manages.
