### ISSUE TITLE
wally not working

### ISSUE THREAD

**Issue by devtyp** [Sleitnick/Knit#216]
hello,
i have a macOS and I am trying to get Knit to work. For some reason, according to foreman everything is installed in the `foreman.toml` file, however, when I run **wally init** my computer tells me that there is no such command. Do you know a fix? Sorry

**Comment by Sleitnick** [comment]
Hello, this is not exactly a Knit issue, so I don't know how much help I will be able to provide. A couple thoughts:

1. Ensure you ran `foreman install` in the same directory as the `foreman.toml` file
2. Similarly, ensure you are running `wally init` in that directory
3. More than likely, you need to [set up your PATH variable](https://github.com/Roblox/foreman#path-configuration) to point to the foreman bin directory
