### ISSUE TITLE
Problem with the Exeuction model.

### ISSUE THREAD

**Issue by zoop1015** [Sleitnick/Knit#218]
So the problem that I'm facing is that I have a service of which has an KnitInit method, and logic within the init method is dependent on other services, but external services are only applicable to be accessed in KnitStart, this becomes an issue.

Am I using structuring my logic wrongly with Knit if this is an issue? If so, how can this be evitable?

**Comment by zoop1015** [comment]
Apologies for this quite-redundant issue! My solution to this is to add yielding logic to asynchronous operations in order to guarantee a successful request.

**Comment by howmanysmall** [comment]
You shouldn't be doing this, this is wrong usage.

You should only be accessing services after Knit has fully started.
