### ISSUE TITLE
Example of how I can handle mouseclick1?

### ISSUE THREAD

**Issue by leonfresh** [Sleitnick/Knit#220]
Hi awesome lib. I want to refactor to this but not sure how to re-wire a localScript that has something like this on it:

```
local ref = script.Parent

ref.MouseButton1Click:Connect(function()	
	RegisterPlayerRemoteEvent:FireServer(localPlayer)
end)

```
I know there is controllers for client side stuff, but are localscript that is bound to the StarterGui like this still needed? And if so how do I set this up?

I couldnt just use a reference for your controller to listen to this MouseButton1Click, it had to be script.Parent somehow.

Watched some of your tuts on youtube and searched the docs but no answers there.

**Comment by howmanysmall** [comment]
This isn't a Knit issue. This is a you issue.

**Comment by leonfresh** [comment]
Yes I'm aware of that, I'm trying to ask a question as I'm new to this lib

> This isn't a Knit issue. This is a you issue.

**Comment by Malakai0** [comment]
Well, I recommend watching some tutorials first.

But if you have a Service with a Client method then you could require the Knit library and obtain the service, and then just use Service:Method().

**Comment by Sleitnick** [comment]
Not relevant to Knit
