### ISSUE TITLE
Knit-created RemoteProperties will sometimes not be available during controller initialization

### ISSUE THREAD

**Issue by enricomfg** [Sleitnick/Knit#224]
There's a very low chance of my service's RemoteProperties being nil (not the value, but the object itself) as seen from the controller/client. There are no reproduction steps and it will occur seemingly spontaneously without code alterations between tests.

**Comment by enricomfg** [comment]
We're running version 1.4.7

**Comment by ambergamefam** [comment]
@Sleitnick 
See: https://github.com/Sleitnick/RbxUtil/issues/155

**Comment by Sleitnick** [comment]
Thanks @ambergamefam and @enricomfg. I'll give this a look this weekend and see if I can resolve it.

**Comment by Sleitnick** [comment]
#248
