### ISSUE TITLE
Allow Services and Controllers to Run in Parallel

### ISSUE THREAD

**Issue by royce-mathew** [Sleitnick/Knit#227]
Would it be possible to create services and controllers and load them under separate actors through Knit?

It would really help if Knit supports this change internally. Because of the way that Knit is implemented, developers have little to no way of implementing Services and Controllers in parallel.

**Comment by AbstractNo** [comment]
I also had a similar issue. This led me to creating my own knit-like framework. Something like this can be implemented by having things such as "ThreadMirrors" which act as an abstraction layer which fires respective bindable events / functions for the desired service.

This would also require a few knit "Instances" to be created for each actor.

**Comment by royce-mathew** [comment]
Have you published this knit-like framework? How do services communicate with each other if they're in separate actors? What happens when you want to access non thread safe variables and methods?

**Comment by AbstractNo** [comment]
Since this is no longer knit related, you can private message me for more details. Just search up TritiiDumoris in users on the Roblox developer forum. I will gladly respond.

**Comment by Sleitnick** [comment]
Knit doesn't really make sense in a parallel context. Perhaps various Knit instances could run different services within different actors and communicate via SharedTables? But that would be very implementation-specific and outside the scope of Knit.
