### ISSUE TITLE
ServiceName must be a string; got table

### ISSUE THREAD

**Issue by CallMeAxis** [Sleitnick/Knit#228]
Followed the tutorial on the docs and YouTube video followed it thoroughly, not sure whats happening here but every time I call the service I get this error.

`ServiceName must be a string; got table`

I'm not sure what really could be causing this,

`local Knit = require(game.ReplicatedStorage.Packages.Knit)
local Signal = require(Knit.Util.Signal)

local MusicService = Knit.CreateService {
	Name = "MusicService",
	Client = {SoundtrackUpdate = Signal.new()},
}
`

**Comment by royce-mathew** [comment]
You don't have to require the signal module to create a signal. You can create a signal directly by doing 
```lua
local Knit = require(game:GetService("ReplicatedStorage"):WaitForChild("Packages").Knit)
local MusicService = Knit.CreateService {
 Name = "MusicService",
 Client = {
  SoundtrackUpdate = knit.CreateSignal();
 }
}
```

**Comment by CallMeAxis** [comment]
Still has the same issue, ServiceName must be a string; got table

**Comment by royce-mathew** [comment]
At the end of the module are you returning MusicService?

**Comment by CallMeAxis** [comment]
Yes i am.

**Comment by royce-mathew** [comment]
Are you able to post the module script here?

**Comment by CallMeAxis** [comment]
Sorry, I accidentally keep clicking the wrong button.

Anyways here is my code.

`local Knit = require(game.ReplicatedStorage.Packages.Knit)
local Signal = require(Knit.Util.Signal)


local MusicService = Knit.CreateService {
	Name = "MusicService",
	Client = {
		SoundtrackUpdate = Knit.CreateSignal();
	}
}

function MusicService:KnitInit()
	print(script.Name .. ": Initalized")
end

function MusicService:KnitStart()
	print(script.Name .. ": Started")
end

-- code --

function MusicService:ServerPlaySoundtrack(soundTrackObject: Sound)
	self.CurrentSoundtrack = soundTrackObject
	soundTrackObject:Play()
	soundTrackObject.Volume = 0
	self.Client.SoundtrackUpdate:Fire(soundTrackObject)
end

function MusicService.Client:GetCurrentPlayingTrack()
	local currentSoundtrack = self.CurrentSoundtrack 
	return currentSoundtrack
end

function MusicService:SetTrackPosition(soundTrackObject: Sound)
	soundTrackObject.TimePosition = self.CurrentSoundtrack.TimePosition
end

return MusicService`

**Comment by royce-mathew** [comment]
You cannot describe functions inside the client table. Instead of doing 
```lua
function MusicService.Client:GetCurrentPlayingTrack()
  local currentSoundtrack = self.CurrentSoundtrack
  return currentSoundtrack
end
```
You could instead, create a remote property for the current soundtrack and use the following documentation. https://sleitnick.github.io/Knit/docs/services#properties

**Comment by wrello** [comment]
Hey, if you haven't solved this yet, I was able to reproduce the error with `Knit.GetService({})`. 

You might possibly be using `Knit:GetService(serviceName)` instead of `Knit.GetService(serviceName)` somewhere in your code base. It's an error I've ran into a few times myself and can be quite confusing if you don't notice the extra dot making it a **":"** instead of a **"."**.
