### ISSUE TITLE
Incorporation of Knit's current effective LTS status into README

### ISSUE THREAD

**Issue by EncodedVenom** [Sleitnick/Knit#229]
Right now, Knit is not receiving any new features, and the last bugfix (as of writing) was in April. Sleitnick has stated that he believes Knit should not be used for new projects, and instead is advocating for a ModuleScript + [Loader](https://sleitnick.github.io/RbxUtil/api/Loader/) + [Net](https://sleitnick.github.io/RbxUtil/api/Net/) approach to preserve intellisense. To give developers more clarity about the project, the README should reflect this.

Additionally, it might be wise to redirect to different projects as referenced within the medium article below.

Reference:
https://medium.com/@sleitnick/knit-its-history-and-how-to-build-it-better-3100da97b36

**Comment by Sleitnick** [comment]
Shifting directions - Knit will be archived soon, so no LTS status will be provided.
