### ISSUE TITLE
Infinite yield possible on 'ReplicatedStorage.Packages.Knit:WaitForChild("Services")'

### ISSUE THREAD

**Issue by SharkTheScripter** [Sleitnick/Knit#231]
![image](https://github.com/Sleitnick/Knit/assets/76228240/5ad5b78f-637b-41bf-847e-06778db3c143)

**Client:**
```lua
local Knit = require(game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"))
Knit.Start():catch(warn):await()
local ReplicationService = Knit.GetService("ReplicationService") -- line 7
```

**Server:**
```lua
local Knit = require(game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("Knit"))
local ReplicationService = Knit.CreateService(
{
	Name = "ReplicationService",
		Client = {
		Data = Knit.CreateProperty(nil)
	}
})
```

**Comment by Sleitnick** [comment]
You need to call `Knit.Start()` on the server too. If you still get this warning, I would suspect that a service is taking a long time to initialize. The `GetService` call on the client will yield indefinitely (hence the warning) until the services are available.
