### ISSUE TITLE
Knit client has script permission error, failing to start

### ISSUE THREAD

**Issue by ambergamefam** [Sleitnick/Knit#234]
I am getting an error preventing the client from starting on Knit v1.5.2
![image](https://github.com/Sleitnick/Knit/assets/122126644/41ecaee0-ca1d-4789-bcc6-ad35d25f31c0)

https://github.com/Sleitnick/Knit/commit/e6c94bd2163e9e567cba783a3239f5af07a80e77#r128355500

**Comment by cuckydev** [comment]
Bumping this, the recent release has broken the initialization process.

**Comment by Sleitnick** [comment]
Fixed. Apologies there. Tried to push some stuff through too fast.
