### ISSUE TITLE
Wait for Service Started

### ISSUE THREAD

**Issue by Shadercloud** [Sleitnick/Knit#236]
I'm using Knit in it's simplest form as I don't want to refactor all my code into Controllers.

If I'm loading a Knit service externally from a client script, what's the best way to wait for the Knit service to be started?  I'm doing it like this:

```
local Knit = require(ReplicatedStorage:WaitForChild("Packages"):WaitForChild("Knit"))
while Knit.startedComplete == false do
    task.wait()
end

local SafeHouseService = Knit.GetService("SafeHouseService")
SafeHouseService.OpenMenu:Connect(function(data)
    -- DO STUFF
end)
```

**Comment by howmanysmall** [comment]
knit.onstart():await() ?

**Comment by Sleitnick** [comment]
The call to `Knit.GetService` on the client will yield until the services are ready. So there's no need to add any extra functionality. You _might_ get a "possible infinite yield" warning if your services are taking a long time, but it's harmless.
