### ISSUE TITLE
No Client table doesn't stop client from using GetService on that service

### ISSUE THREAD

**Issue by mwc441** [Sleitnick/Knit#245]
If you omit the Client table when creating a service, it doesn't stop the client from calling "GetService" on that service, or atleast it doesnt error out?

I've tried parsing through the code to see if i could interpret what is going on, but i didnt see anything that's stopping the client from getting a service that has no client table. A folder is still created for the service, which is quite a security concern if the service is meant to be server only.

According to the documentation a service without a client table is server-side only

**Comment by Sleitnick** [comment]
There is no way for the client to get into those services as there are no RemoteEvents/Functions exposed. While a folder might exist, that does not provide any security risk whatsoever.
