### ISSUE TITLE
Automatic Roblox deploys

### ISSUE THREAD

**Issue by Dog2puppy** [Sleitnick/Knit#3]
Rojo or [Remodel](https://github.com/Roblox/remodel) should be used to automatically build and deploy new releases to the Roblox asset.

**Comment by Sleitnick** [comment]
Not sure I can do this without exposing sensitive cookie info

**Comment by Dog2puppy** [comment]
You could move the Knit module to a group and then add a bot to the group. Also, I believe stuff stored in secrets is never exposed to any pull requests.

**Comment by Sleitnick** [comment]
Completed in https://github.com/Sleitnick/Knit/releases/tag/v0.0.7-alpha
