### ISSUE TITLE
Documentation Errors

### ISSUE THREAD

**Issue by osyrisrblx** [Sleitnick/Knit#33]
https://sleitnick.github.io/Knit/services/#full-example
Second code block uses `Event.new()`, but I think this should be `RemoteEvent.new()`? Not 100% sure.

https://sleitnick.github.io/Knit/controllers/#events
`Locked` is reused as both a property (previous example) and an event (this example).
Either the property should be `isLocked` or the event should be `OnLocked`.

**Comment by Sleitnick** [comment]
Good catches. For the first one, the ones at the top-level of the service should be Signal and the ones under Client should be RemoteEvent (soon to be RemoteSignal).
