### ISSUE TITLE
Add Error handling when KnitServer hasnt been started

### ISSUE THREAD

**Issue by HawDevelopment** [Sleitnick/Knit#74]
https://github.com/Sleitnick/Knit/blob/56fd149deb97ada007c995936da9f21eec11ed92/src/Knit/KnitClient.lua#L29

KnitClient stops if KnitServer isnt started, this should instead error or add a some other design.
This means if the server isnt started or the serverfolder is destroyed all other clients wont start.

I think it should error instead, and KnitClient.Start() should return a rejected Promise.

**Comment by ok-nick** [comment]
Using `Start`, KnitClient would yield until the server is ready and loaded. Immediately returning an error can break many cases where the client loads faster than the server. Although one can argue there should be a timeout until error... no. Something like this could determine if a user is even able to play your game. Maybe a warning could suffice for unusual loading times, but technically that is already supplied by a infinity yield from `WaitForChild`.

**Comment by Sleitnick** [comment]
I agree with @ok-nick that `WaitForChild` will bring in a warning. However, there could be a case of adding something like an attribute to indicate the server's current startup state to the client.
