### ISSUE TITLE
Tutorial & Project Example

### ISSUE THREAD

**Issue by Sleitnick** [Sleitnick/Knit#86]
Knit needs a tutorial series, where an game project is constructed using Knit. The project will also be open-sourced.

**Comment by Sleitnick** [comment]
The first video has been made, where a game is constructed from scratch. More videos are still needed to go into detail about the various utility modules.

https://www.youtube.com/playlist?list=PLk3R4TM3pnqusf59x2tZ8f-5vE2c3L5S9

**Comment by jwisham** [comment]
I would really like to see a better, more beginner friendly example in README.md about using Rojo and Wally, including where to insert Knit as a wally dependency.
You could also create a video on how to add knit to a Rojo/Wally project.
With how popular this package is, I could see Knit being the reason many devs switch to a Rojo/Wally workflow.
P.S. - Congrats on the recent wedding!

**Comment by jwisham** [comment]
Retracted my previous comment, rephrasing it here.
I would like to see a video on how to use Knit with the Rojo/Wally workflow, and how to set up a project using Rojo and Wally.
With how popular Knit is, I believe this being out there may cause more developers to start using this workflow over using studio on it's own.
P.S. Congrats on the wedding!

**Comment by Sleitnick** [comment]
@jwisham I agree, I need to redo the tutorial to show the new workflow

**Comment by Sleitnick** [comment]
https://www.youtube.com/watch?v=q-wLraP2hF8
