### ISSUE TITLE
Add a DependsOn feature for components

### ISSUE THREAD

**Issue by Sleitnick** [Sleitnick/Knit#90]
For the sake of good composition, it would be nice if components had a "depends on" feature which would allow developers to indicate if a component must depend on other components to exist first.

For instance, there might be a top-level "Vehicle" component, and other lower-level components (e.g. "Motorcycle") might depend on the Vehicle component. Currently, a lot of custom code has to be written to make this guarantee. This is not ideal, and there should be a built-in feature to accommodate for this need.

For instance, components could have an optional DependsOn table which would list out the components that must exist for itself to instantiate:

```lua
local Motorcycle = {}
Motorcycle.__index = Motorcycle

-- Depend on the Vehicle component existing:
Motorcycle.DependsOn = {"Vehicle"}

function Motorcycle.new(instance)
	local self = setmetatable({}, Motorcycle)

	-- We can now guarantee this will return the Vehicle component:
	self.Vehicle = Component.FromTag("Vehicle"):GetFromInstance(instance)

	return self
end
...
```

Rules:
1. Only when _all_ of the `DependsOn` components are available will the component be instantiated.
2. If _any_ of the `DependsOn` components become unavailable, the component will be destroyed.

**Comment by Sleitnick** [comment]
Perhaps this optional table could be named `RequireComponents` to be similar to Unity's `RequireComponent` attribute? However, the difference is that this will _not_ instantiate a missing component, but rather wait for it to exist.

**Comment by ok-nick** [comment]
`needs` sounds nice; taken from GitHub actions when requiring other jobs to complete first.
