### ISSUE TITLE
Re write some portion of the signal modules to support Deferred Lua Event Handling as well as signal usage in Knit

### ISSUE THREAD

**Issue by SilentsReplacement** [Sleitnick/Knit#93]
[Deferred Lua Event Handling](https://devforum.roblox.com/t/beta-deferred-lua-event-handling/1240569) was recently released, and Knit should support it right now or when it comes out of beta.  Signals will have undefined and unexpected behaviour  and a lot of signal modules have been affected by this change. Knit internally also uses signals, which means it may have been affected by this as well, and I my self am seeing these behaviours when using the custom signal module of Knit.

**Comment by Sleitnick** [comment]
Yup, actually beginning work on this today since I just got back from vacation.

**Comment by SilentsReplacement** [comment]
> Yup, actually beginning work on this today since I just got back from vacation.

Here are some errors I found while turning on deferred enabled:

![image](https://user-images.githubusercontent.com/71311544/120076632-f5cbe900-c0bf-11eb-9d49-414726b8fa0c.png)

![image](https://user-images.githubusercontent.com/71311544/120076651-1a27c580-c0c0-11eb-83eb-7485ec49f6f5.png)

**Comment by SilentsReplacement** [comment]
Any updates on this? The fact that events are deferred are a problem, since they are going to cause a noticeable latency as well. Can you maybe get rid of the bindable based approach and switch to a table based instead?

**Comment by SilentsReplacement** [comment]
@Sleitnick I've found the issue with the signal module, and have found a fix for it. What happened was that upon deferred enabled, `Signal:DisconnectAll` would expect that `Signal:Wait` or `Signal:Connect()` would be resumed immediately, when in fact in deferred, event handlers / threads are resumed at a later time and would set `self._args` and `self._connections` to nil which would cause a problem.

Solution:

Wait until all threads / handlers have resumed / completed:

```
function Signal:DisconnectAll()
	for _,c in ipairs(self._connections) do
		if (c._conn) then
			c._conn:Disconnect()
		end
	end
	
	if self._threadsLeft > 0 then
		self._threadsCompleted.Event:Wait()
	end
	
	if self._handlersLeft > 0 then
		self._handlersCompleted.Event:Wait()
	end
	
	self._connections = {}
	self._args = {}
end
```

I will send a pull request now.

**Comment by SilentsReplacement** [comment]
@Sleitnick See my latest [pull request](https://github.com/Sleitnick/Knit/pull/113) for the complete fix and support for deferred events.
