### ISSUE TITLE
Using classes with a service on controller breaks since version 0.7

### ISSUE THREAD

**Issue by grilme99** [Sleitnick/Knit#95]
I originally wrote this issue for the [roblox-ts port of Knit](https://github.com/osyrisrblx/rbxts-knit), but am posting it here so that the issue can be solved upstream without a hack.

We're currently blocked from upgrading `@rbxts/knit` past version 0.6 because our "class method" no longer works. There are no errors and Knit reports that everything has started properly, but nothing runs. Since that version, Knit uses `TableUtil.Assign()` for `Knit:CreateService()`/`Knit:CreateController()`, which shallow copies the service/controllers tables and strips any metatable from them.

Our service and controller definitions look like this:
```typescript
export const ExampleController = Knit.CreateController(
    new (class ExampleController extends KnitController {
        public Name = "ExampleController";

        public KnitStart() {}
    })(),
);
```
We do this because it is much easier to work in a class rather than an object (which is used by default). In Typescript, there's a lot of advantages to working with a class in this context, rather than an object, such as private members. 

The emit of the above code is a generic Lua class, which relies on metatables to function. When the metastable is removed, Knit can't find any methods on it (including `KnitInit` and `KnitStart`). Here's the emit on the [roblox-ts playground](https://roblox-ts.com/playground/#code/JYWwDg9gTgLgBAbzgaQHbBgYQDbAKarwCGAziuvAL5wBmUEIcARAAJQBGAHjCQPQDWFJgChheTpFhwAxhFQl4AUU5Fw2PJjkx62dVDgBechgB0mKHiIwNWnXoAUwuM7io8Adzj3p2UmWWqYOqahHZ4+ghOLtFgAK7suNJwAHKqeIbMAWo2oRC64UwA3KLRMfGJxjAAyjBEsPYAlIiUUc6UDY0ANMINhUA), if you want to inspect it.

**Comment by Sleitnick** [comment]
I wonder if copying over the metatable would solve this? If I'm understanding this correctly, the issue is really that `TableUtil` was switched to avoid mutating tables, which in turn changed how the CreateController/CreateService functions worked. The current code (without the assertions) looks like this:

```lua
function KnitClient.CreateController(controller)
	controller = TableUtil.Assign(controller, {
		_knit_is_controller = true;
	})
	KnitClient.Controllers[controller.Name] = controller
	return controller
end
```

But what if I did something like this:

```lua
function KnitClient.CreateController(controller)
	local mt = getmetatable(controller)
	controller = TableUtil.Assign(controller, {
		_knit_is_controller = true;
	})
	setmetatable(controller, mt)
	KnitClient.Controllers[controller.Name] = controller
	return controller
end
```

Would preserving the metatable solve this problem? I see no issue with adding something like this.

**Comment by grilme99** [comment]
That would solve the problem perfectly! Right now we have a workaround which does this same thing (see the [issue](https://github.com/osyrisrblx/rbxts-knit/issues/5) in the roblox-ts port).
