### ISSUE TITLE
Component.Auto(folder) doesn't account for folders nested inside the folder it self

### ISSUE THREAD

**Issue by SilentsReplacement** [Sleitnick/Knit#97]

**Comment by Sleitnick** [comment]
It does account for nested modules. [`Component.Auto()`](https://github.com/Sleitnick/Knit/blob/main/src/Util/Component.lua#L155) uses `GetDescendants` to scan through and pull any ModuleScripts. It also sets up a `DescendantsAdded` handler in case any modules are added after-the-fact (good for client-side situations where `Auto` is called on a folder where not all modules have potentially loaded).

**Comment by SilentsReplacement** [comment]
Weird, I'm aware it does uses `GetDescendants` but for now I've start them up manually.
